blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/rheedwahn/session-guardian/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issue
    url: https://github.com/rheedwahn/session-guardian/security/advisories/new
    about: Report a security vulnerability privately
  - name: 📖 Documentation
    url: https://github.com/rheedwahn/session-guardian/blob/main/README.md
    about: Read the documentation and development guide
